# Generated by Django 4.1.3 on 2022-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
