# Generated by Django 4.1.3 on 2022-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_wallet_email_alter_wallet_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(default='recipient', max_length=300),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(default='sender', max_length=300),
        ),
    ]
